### ISSUE TITLE
Testing weightcalc - pathos module issues

### ISSUE THREAD

**Issue by SimonStreicher** [SimonStreicher/FaultMap#15]
The pathos module gives an error when attempting to run `test_weightcalc.py`.

Any clue on how to fix it will be appreciated.

**Comment by alchemyst** [comment]
I am currently unable to install pathos with pip. Do we really need it? What benefits are there above the built-in `multiprocessing` module?

**Comment by SimonStreicher** [comment]
Pathos solves some pickling issues with the Java class being called from within another class by using dill instead in the multiprocessing pooling.

**Comment by SimonStreicher** [comment]
It does not install from pip, that's why I used the commands seen in `.travis.yml`.

**Comment by alchemyst** [comment]
Is it crucial to install the 0.1a1 version first and then the git version?

**Comment by SimonStreicher** [comment]
Yes, as far as I understand it has something to do with other packages being customized in the 0.1a1 version that is not included in the git version.

**Comment by alchemyst** [comment]
I've been working on .travis.yml for a while now this weekend. The original version had a problem with the scipy version installed, but I appear to have broken the pathos install now. This dependency is a nightmare to get running - is there really no way around it? Perhaps we can just run the tests without multiprocessing?

**Comment by alchemyst** [comment]
PS: I have also been unable to get it installed on my local machine or on my AWS ubuntu image.

**Comment by alchemyst** [comment]
Ah! It appears I have got the install process right now, replicating your error on travis. Since I haven't been able to get pathos running on my machine, I've not been able to replicate the issue locally, but I think I may now be able to. I will have a look at it later this week.

**Comment by SimonStreicher** [comment]
The tests are passing now.
