### ISSUE TITLE
Travis times out

### ISSUE THREAD

**Issue by SimonStreicher** [SimonStreicher/FaultMap#17]
Travis times out when requested to do multiprocessing. However, the tests takes mere seconds to run locally.

**Comment by alchemyst** [comment]
This issue has gone away/has been fixed. I'm pretty sure this was a temporary problem with the Java on the travis machine.

**Comment by SimonStreicher** [comment]
I forgot to mention that this was on the `dev_active` branch.

**Comment by alchemyst** [comment]
Ah, I see the issue appears to be with multiprocessing. I suggest we create a test case that tests the multiprocessing more orthogonally. The test suite is actually a bit weak at the moment, as it doesn't try to test things separately, which makes debugging quite hard. I've got the .travis.yml working quite well now, with the latest scipy installed from condas and a small tex support to suppress some of the matplotlib warnings.

**Comment by alchemyst** [comment]
I can verify that the tests hang on my Mac as well, so it's a more general problem than the travis machine.

**Comment by SimonStreicher** [comment]
This has been fixed. Not sure exactly when.
