### ISSUE TITLE
Revisit dependencies

### ISSUE THREAD

**Issue by alchemyst** [SimonStreicher/FaultMap#19]
I don't think we still use python-igraph as a dependency (I could find a file which imported it). I think we should revise `requirements.txt`, `conda-requirements.txt` and `sphinx_requirements.txt`.

**Comment by SimonStreicher** [comment]
Dependencies revisited extensively.
Dependency on pyunicorn removed - single function implemented in own code, required a lot of other packages that were unnecessary.

**Comment by alchemyst** [comment]
If you have also made sure that the various dependency lists are now correct, you can close this issue.

**Comment by SimonStreicher** [comment]
Removed `sphinx_requirements.txt` for now, will add back later if necessary but I expect it will now be fine with being identical to `requirements.txt`. All dependencies can now be installed with pip if need, conda is used where available.
